export const GET_ALL_PHOTOS = 'GET_ALL_PHOTOS';
export const GET_PHOTO_OF_CLICKED_BREED = 'GET_PHOTO_OF_CLICKED_BREED';
export const GET_RANDOM_PHOTO = 'GET_RANDOM_PHOTO';
export const PHOTOS_ERROR = 'PHOTOS_ERROR';
export const RESET_CLICKED_PHOTO = 'RESET_CLICKED_PHOTO';
export const RESET_RANDOM_PHOTO = 'RESET_RANDOM_PHOTO'